services:
  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2

  backend1:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8081:8081"

  backend2:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8082:8082"
