apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: sa4dus/backend2:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend2
spec:
  selector:
    app: backend2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None
